name: gtk-3-test
version: "0.1"
summary: gtk-3-test
description: |
  gtk-3-test

grade: stable
confinement: strict
base: core18

parts:
  gtk3-widget-factory:
    plugin: nil
    stage-packages:
      - gtk-3-examples
    prime:
      - usr/share/applications/gtk3-demo.desktop
      - usr/bin/gtk3-demo
      - usr/share/applications/gtk3-widget-factory.desktop
      - usr/bin/gtk3-widget-factory
apps:
  gtk3-widget-factory:
    command: usr/bin/gtk3-widget-factory
    desktop: usr/share/applications/gtk3-widget-factory.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - pulseaudio
      - unity7
      - x11
    extensions: [gnome-3-28]
  gtk3-demo:
    command: usr/bin/gtk3-demo
    desktop: usr/share/applications/gtk3-demo.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - pulseaudio
      - unity7
      - x11
    extensions: [gnome-3-28]
